CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    login TEXT UNIQUE NOT NULL,
    hasloHash TEXT NOT NULL,
    rola TEXT NOT NULL DEFAULT 'USER',
    created_at TEXT NOT NULL
);
